
# Install Docker on different Linux distributions
---
- name: Install dependencies for Ubuntu/Debian
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  when: ansible_os_family == "Debian"

- name: Install Docker on Ubuntu/Debian
  apt:
    name: docker-ce
    state: present
  when: ansible_os_family == "Debian"

- name: Install dependencies for CentOS/RHEL
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  when: ansible_os_family == "RedHat"

- name: Install Docker on CentOS/RHEL
  yum:
    name: docker-ce
    state: present
  when: ansible_os_family == "RedHat"

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
